name: art
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_storage: ^11.5.0
  cloud_firestore: ^4.12.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  riverpod: ^2.4.5
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
