// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Zvac1zSOrvDK5xddZzWU5F82Q26efYU',
    appId: '1:380449542449:web:5f522b7d04504483d3e010',
    messagingSenderId: '380449542449',
    projectId: 'artproject-ff861',
    authDomain: 'artproject-ff861.firebaseapp.com',
    storageBucket: 'artproject-ff861.firebasestorage.app',
    measurementId: 'G-X1NEXXLJ8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIOSWPFyPB_nVcR95vBrHf-b7Z7wMHqSw',
    appId: '1:380449542449:android:80804936b33da330d3e010',
    messagingSenderId: '380449542449',
    projectId: 'artproject-ff861',
    storageBucket: 'artproject-ff861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDUBu7tsz3H8NshILvzTiaOj-T0ZfBOA',
    appId: '1:380449542449:ios:baf45e6aec3f1084d3e010',
    messagingSenderId: '380449542449',
    projectId: 'artproject-ff861',
    storageBucket: 'artproject-ff861.firebasestorage.app',
    iosBundleId: 'com.example.art',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdDUBu7tsz3H8NshILvzTiaOj-T0ZfBOA',
    appId: '1:380449542449:ios:baf45e6aec3f1084d3e010',
    messagingSenderId: '380449542449',
    projectId: 'artproject-ff861',
    storageBucket: 'artproject-ff861.firebasestorage.app',
    iosBundleId: 'com.example.art',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Zvac1zSOrvDK5xddZzWU5F82Q26efYU',
    appId: '1:380449542449:web:37076ff248d58aabd3e010',
    messagingSenderId: '380449542449',
    projectId: 'artproject-ff861',
    authDomain: 'artproject-ff861.firebaseapp.com',
    storageBucket: 'artproject-ff861.firebasestorage.app',
    measurementId: 'G-GZ067JNHHE',
  );
}
